### ISSUE TITLE
[Feat]admin 댓글관리 포스트이동, 카테고리 이름 수정 기능

### ISSUE THREAD

**Issue by seon022** [prgrms-fe-devcourse/NFE1_2_3_Clogging#108]
## 💡 기능 추가
> 추가하려는 기능에 대해 간단하게 설명 부탁드립니다!
-  댓글관리 목록에서 클릭 시 해당 페이지로 이동
- 카테고리 이름 수정 기능

## ✏️ TO-DO
> 해야 할 일 목록을 작성해주세요!
- [x] 댓글관리 목록에서 클릭 시 해당 페이지로 이동
- [x] 관리자 댓글 프로필사진 출력
- [x] 카테고리 추가 시 중복확인
- [x] 카테고리 이름 수정 기능
- [x] 답글 삭제 에러 수정..

## 📚 참고자료
> 참고할 자료가 있다면 첨부해주시거나 작성해주세요!
