### ISSUE TITLE
[Feat] 공통 네비게이션 테마 모드 전역 관리 기능 추가

### ISSUE THREAD

**Issue by sssssubin** [prgrms-fe-devcourse/NFE1_2_3_Clogging#11]
## 💡 기능 추가
> 추가하려는 기능에 대해 간단하게 설명 부탁드립니다!
- 전체 애플리케이션에서 일관된 테마 모드(다크/라이트) 적용
- 사용자의 테마 설정 유지를 위한 로컬 스토리지 활용
- 시스템 테마 설정과의 동기화

## ✏️ TO-DO
> 해야 할 일 목록을 작성해주세요!
- [x] ThemeContext 생성 및 Provider 구현
- [x] 테마 모드 상태 관리 로직 구현
  - [x] 로컬 스토리지 연동
  - [x] 시스템 테마 감지
- [x] Navigation 컴포넌트에 테마 모드 적용
- [x] 메인 페이지 테마 모드 적용

## 📚 참고자료
> 참고할 자료가 있다면 첨부해주시거나 작성해주세요!
