### ISSUE TITLE
[Feat] 메인페이지 구성

### ISSUE THREAD

**Issue by hjlee2778** [prgrms-fe-devcourse/NFE1_2_3_Clogging#2]
## 💡 기능 추가
> 추가하려는 기능에 대해 간단하게 설명 부탁드립니다!

사용자가 메인 페이지에서 카드 형태로 포스트에 대한 정보를 확인할 수 있습니다. 

## ✏️ TO-DO
> 해야 할 일 목록을 작성해주세요!
- [ ] 사용자는 포스트 카드를 누르면 해당 포스트의 상세 페이지로 이동할 수 있습니다.
- [x] 사용자는 블로그 관리자의 프로필에 대한 정보를 확인할 수 있습니다.
- [x] 사용자는 누적된 포스트 카드를 스크롤을 통해 확인할 수 있습니다.

## 📚 참고자료
> 참고할 자료가 있다면 첨부해주시거나 작성해주세요!
