### ISSUE TITLE
[Feat] 인트로 페이지 구현

### ISSUE THREAD

**Issue by sssssubin** [prgrms-fe-devcourse/NFE1_2_3_Clogging#32]
## 💡 기능 추가
> 추가하려는 기능에 대해 간단하게 설명 부탁드립니다!
- 일반 사용자, 관리자 구분 기능
## ✏️ TO-DO
> 해야 할 일 목록을 작성해주세요!
- [x] 일반 사용자, 관리자 버튼 구현
- [x] 관리자 버튼 클릭 시 인증 기능 구현
- [x] 관리자 인증 후 네비게이션에 관리자 메뉴 노출

## 📚 참고자료
> 참고할 자료가 있다면 첨부해주시거나 작성해주세요!
