### ISSUE TITLE
[Feat]admin 페이지 - 통계 페이지 ui

### ISSUE THREAD

**Issue by seon022** [prgrms-fe-devcourse/NFE1_2_3_Clogging#37]
## 💡 기능 추가
> 추가하려는 기능에 대해 간단하게 설명 부탁드립니다!

- admin페이지에서 통계 페이지의 ui구현

## ✏️ TO-DO
> 해야 할 일 목록을 작성해주세요!
- [x] 통계 페이지 ui구현
- [x] charting 라이브러리 (Recharts) 적용 예정
- [ ] React Activity Calendar 적용 예정

## 📚 참고자료
> 참고할 자료가 있다면 첨부해주시거나 작성해주세요!
