### ISSUE TITLE
[Feat] 포스팅 API 연동하여 기능 구현하기

### ISSUE THREAD

**Issue by gd06070** [prgrms-fe-devcourse/NFE1_2_3_Clogging#65]
## 💡 기능 추가
> 추가하려는 기능에 대해 간단하게 설명 부탁드립니다!

- 마크업이 드디어 완료된,,, 포스팅 페이지를 API 와 연동시켜서 기능을 구현하고자 합니다 !

## ✏️ TO-DO
> 해야 할 일 목록을 작성해주세요!
- [x] posts API 연동하기
- [x] tags API 연동하기
- [x] categories API 연동하기
- [ ] firebase 이미지 데이터 불러오기
- [x] 사용자 생성 태그 DB 저장 확인
- [x] firebase DB에 등록한 포스트 데이터 저장 확인 
- [x] 뒤로가기 버튼을 이전 페이지와 연결

## 📚 참고자료
> 참고할 자료가 있다면 첨부해주시거나 작성해주세요!

- 저의 소중한 API 를 적극적으로 활용할 생각입니다,,,!
