### ISSUE TITLE
[Feat] 파이어베이스에 관리자 인증 컬렉션 추가 및 비밀번호 인증 로직 구현

### ISSUE THREAD

**Issue by sssssubin** [prgrms-fe-devcourse/NFE1_2_3_Clogging#76]
## 💡 기능 추가
> 추가하려는 기능에 대해 간단하게 설명 부탁드립니다!
- 관리자 비밀번호 설정 및 관리 기능 추가
- /admin/init 페이지에서 최초 비밀번호 설정 가능
- 초기 비밀번호 설정되지 않은 경우 자동으로 /admin/init 초기 설정 페이지로 리다이렉트 됨
- /admin/settings 페이지에서 비밀번호 변경이 가능
- INITIAL_PASSWORD 상수값에 초기 비밀번호 세팅

## ✏️ TO-DO
> 해야 할 일 목록을 작성해주세요!
- [x]  Firebase에 관리자 인증용 컬렉션 생성
- [x] 관리자 비밀번호 인증 로직 구현
- [x] 비밀번호 설정/변경 기능 구현
- [x] 페이지 접근 권한 관리

## 📚 참고자료
> 참고할 자료가 있다면 첨부해주시거나 작성해주세요!
