### ISSUE TITLE
[Feat] 관리 페이지 배너, 이미지 등 저장상태 확인 및 홈 ,피드 페이지에 연결

### ISSUE THREAD

**Issue by hjlee2778** [prgrms-fe-devcourse/NFE1_2_3_Clogging#82]
## 💡 기능 추가
> 추가하려는 기능에 대해 간단하게 설명 부탁드립니다!
- 관리 페이지에서 저장이 잘 되는지, 오류가 발생하지 않는지 확인
- 제대로 저장 되고 오류 발생하지 않으면 해당 정보 홈 및 피드 페이지에 연동하기

## ✏️ TO-DO
> 해야 할 일 목록을 작성해주세요!
- [ ] 관리자 페이지 오류 발생 확인
- [ ] 홈 페이지에 관리자 정보 연동
- [ ] 피드 페이지에 배너 사진 연동

## 📚 참고자료
> 참고할 자료가 있다면 첨부해주시거나 작성해주세요!
