### ISSUE TITLE
[Fix]블로그 관리 이미지 등록 UI 수정

### ISSUE THREAD

**Issue by seon022** [prgrms-fe-devcourse/NFE1_2_3_Clogging#86]
## 💡 기능 추가
> 추가하려는 기능에 대해 간단하게 설명 부탁드립니다!
- 개발 중 출력 테스트해보려고 추가해놓은 이미지 UI 수정

## ✏️ TO-DO
> 해야 할 일 목록을 작성해주세요!
- [x] 블로그 관리 페이지 디자인 구현
- [x] 등록된 이미지 제거 기능
- [x] 파비콘 동적 적용

## 📚 참고자료
> 참고할 자료가 있다면 첨부해주시거나 작성해주세요!
