### ISSUE TITLE
[Feat]  스타일 가이드 시스템 구축

### ISSUE THREAD

**Issue by sssssubin** [prgrms-fe-devcourse/NFE1_2_3_Clogging#9]
## 💡 기능 추가
> 추가하려는 기능에 대해 간단하게 설명 부탁드립니다!

## ✏️ TO-DO
> 해야 할 일 목록을 작성해주세요!
- [ ] Tailwind CSS 커스텀 설정
- [ ] 공통 컴포넌트를 위한 스타일 가이드 시스템 구축
- [ ] 공통 컴포넌트 구현

## 📚 참고자료
> 참고할 자료가 있다면 첨부해주시거나 작성해주세요!
