### ISSUE TITLE
[Fix] 다크모드에서 상세페이지 색 수정

### ISSUE THREAD

**Issue by hjlee2778** [prgrms-fe-devcourse/NFE1_2_3_Clogging#98]
## 💡 기능 추가
> 추가하려는 기능에 대해 간단하게 설명 부탁드립니다!
- 다크모드에서 상세 포스트 페이지 색이 겹치는 부분 수정하겠습니다.
- 댓글 영역에서 하얗게 처리되는 부분 수정하겠습니다.
- 페이지네이션 박스도 알맞게 수정하겠습니다.

## ✏️ TO-DO
> 해야 할 일 목록을 작성해주세요!
- [x] 포스트 제목 색 수정
- [x] 페이지네이션 박스 호버 색 수정
- [x] 댓글 카드 색 수정

## 📚 참고자료
> 참고할 자료가 있다면 첨부해주시거나 작성해주세요!
